namespace OoplesFinance.YahooFinanceAPI.Enums;

public enum YahooModule
{
    AssetProfile,
    BalanceSheetHistory,
    BalanceSheetHistoryQuarterly,
    CalendarEvents,
    CashflowStatementHistory,
    CashflowStatementHistoryQuarterly,
    Earnings,
    EarningsHistory,
    EarningsTrend,
    EsgScores,
    FinancialData,
    FundOwnership,
    FundProfile,
    IncomeStatementHistory,
    IncomeStatementHistoryQuarterly,
    IndexTrend,
    InsiderHolders,
    InsiderTransactions,
    Insights,
    InstitutionOwnership,
    KeyStatistics,
    MajorDirectHolders,
    MajorHoldersBreakdown,
    NetSharePurchaseActivity,
    Price,
    QuoteType,
    RecommendationTrend,
    SecFilings,
    SectorTrend,
    SummaryDetails,
    UpgradeDowngradeHistory
}
