global using OoplesFinance.YahooFinanceAPI.Models;
global using OoplesFinance.YahooFinanceAPI.Enums;
global using OoplesFinance.YahooFinanceAPI.Helpers;
global using System.Globalization;
global using System.Net;
global using static OoplesFinance.YahooFinanceAPI.Helpers.DownloadHelper;
global using static OoplesFinance.YahooFinanceAPI.Helpers.UrlHelper;
global using OoplesFinance.YahooFinanceAPI.Interfaces;
global using System.Text.Json.Serialization;
global using System.Net.Http.Json;
global using System.Text.Json;
global using System.Text.Encodings.Web;
global using Newtonsoft.Json;